# -*- coding: utf-8 -*-
"""DarVisAdi_EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tR-uQ6Vt0o4hXXShw4lUKlENz7NarCmw
"""

import pandas as pd
titanic = pd.read_excel(r'titanic3.xls')
titanic.head(2)

# null, no.of, no.of rows, data type of the columns -- info
titanic.info()

titanic.columns

titanic.columns

titanic.isnull().sum()

import seaborn as sn
sn.heatmap(titanic.isnull(),cmap='RdPu')

# drop the columns having null values
# titanic.drop(['cabin','boat', 'body', 'home.dest','name'], axis=1, inplace=True)
# drop the rows having null values
# titanic.dropna(inplace=True, axis=0)
# verify the data
# titanic.isnull().sum()
titanic.info()

# Preprocessing -- changing text to number
from sklearn.preprocessing import LabelEncoder
# model, fit the data to the model
gen_le = LabelEncoder()
titanic['gender_new'] = gen_le.fit_transform(titanic['gender'])
titanic

from sklearn.preprocessing import LabelEncoder
emb_le = LabelEncoder()
titanic['embarked'] = emb_le.fit_transform(titanic['embarked'])

titanic.drop(['sibsp','parch','ticket','gender'], axis=1, inplace=True)

# count of passengers for each class
titanic['pclass'].value_counts().plot(kind='pie', autopct='%1.2f%%', cmap='Set3')

# count of passengers for each gender
titanic['gender_new'].value_counts().plot(kind='bar')

# 
pd.crosstab([titanic['pclass'],titanic['gender_new']],titanic['survived']).plot(kind='barh', cmap='viridis')

# gender based survival
# pclass based survival
# gender and pclass based survival count

titanic['age'].plot(kind='hist',bins=200)

from matplotlib import pyplot as plt
x=[12,23,34,43,23,34,45,52,26,67,78,65,45,34,37,15,24,46]
plt.hist(x, bins=100)

